version: '2.4'
services:
  yolo:
    image: yolo
    container_name: yolov8_ros
    privileged: true
    build:
      context: ../object_detectors/yolov8_sasha/docker
      dockerfile: dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../object_detectors/yolov8_sasha/:/root/yolo
      - "../data/weights/yolov8:/root/yolo/weights:rw"
      - ../config:/root/config
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - DATASET=${DATASET}
    env_file: ../config/ros.env
    command: bash -c "source catkin_ws/devel/setup.bash;
                      python ./yolo/detect_ros_seg.py --conf-thres 0.8 --weights ./yolo/weights/${DATASET}.pt --camera-topic '$$(rosparam get /pose_estimator/color_topic)'"

    stdin_open: true
    tty: true 

  gdrnpp:
    image: gdrnpp
    container_name: gdrnpp_ros
    build:
      context: ../pose_estimators/gdrnpp_sasha/docker
      dockerfile: dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../pose_estimators/gdrnpp_sasha/:/root/gdrnpp:rw"
      - ../pose_estimators/gdrnpp_sasha/.torch_cache:/root/.cache/torch
      - ../config:/root/config
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - "../data/weights/gdrnpp:/root/gdrnpp/output:rw"
      - "../data/datasets:/root/gdrnpp/datasets/BOP_DATASETS:rw"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - DATASET=${DATASET}
    env_file: ../config/ros.env
    command: bash -c "source catkin_ws/devel/setup.bash;  rosparam load /root/config/${CONFIG} /pose_estimator; python ./gdrnpp/core/gdrn_modeling/demo/demo_gdrn_ros_robokudo.py --dataset_name ${DATASET}"        
    stdin_open: true
    tty: true